openapi: 3.0.3
info:
  title: Laravel StarterPack API
  description: Laravel StarterPack API endpoint'leri
  version: 1.0.0
  contact:
    name: Beyazıt Kölemen
    email: beyazit@artf4.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://starter-pack.test/api
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  $ref: './paths/auth.yaml'

components:
  schemas:
    $ref: './schemas/index.yaml'
  securitySchemes:
    $ref: './security/index.yaml'

tags:
  $ref: './tags/index.yaml'
